# Generated by Django 4.1 on 2022-12-03 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailedUserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(default='-', max_length=10)),
                ('phone_number', models.CharField(default='', max_length=15)),
                ('pekerjaan', models.CharField(default='', max_length=30)),
                ('alamat', models.TextField(default='')),
                ('tanggal_lahir', models.CharField(default='-', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
