# Generated by Django 4.1 on 2022-11-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detaileduserdata',
            name='alamat',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='detaileduserdata',
            name='pekerjaan',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='detaileduserdata',
            name='tanggal_lahir',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='detaileduserdata',
            name='gender',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='detaileduserdata',
            name='phone_number',
            field=models.IntegerField(default=''),
        ),
    ]
