# Generated by Django 4.1 on 2022-12-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detaileduserdata',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
    ]
