# Generated by Django 4.1 on 2022-11-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='nama',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='pesan_feedback',
            field=models.TextField(null=True),
        ),
    ]
