# Generated by Django 4.1 on 2022-12-03 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('daftarwilayah', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pendaftaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keahlian', models.CharField(max_length=50)),
                ('mulai_periode', models.DateTimeField()),
                ('akhir_periode', models.DateTimeField()),
                ('relawan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wilayah', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='daftarwilayah.wilayah')),
            ],
        ),
    ]
