# Generated by Django 4.1 on 2022-11-02 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daftarrelawan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daftarrelawan',
            old_name='mulai_periode',
            new_name='ulai_periode',
        ),
    ]
