# Generated by Django 4.1 on 2022-11-02 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daftarrelawan', '0002_rename_mulai_periode_daftarrelawan_ulai_periode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daftarrelawan',
            old_name='ulai_periode',
            new_name='mulai_periode',
        ),
    ]
