# Generated by Django 4.1 on 2022-11-02 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daftarwilayah', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('daftarrelawan', '0003_rename_ulai_periode_daftarrelawan_mulai_periode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daftarrelawan',
            name='Relawan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='daftarrelawan',
            name='Wilayah',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='daftarwilayah.wilayah'),
        ),
    ]
