# Generated by Django 4.1 on 2022-11-02 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donasi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donasi',
            options={'ordering': ['-pk']},
        ),
    ]
